### ISSUE TITLE
[BUG][10.0][product_contract] Product_contract: unable to confirm SO

### ISSUE THREAD

**Issue by ygol** [OCA/contract#138]
Testing product_contract.
expecting to have a contract automatically created when added to a SO

problem: cannot validate SO

repoduce:
-Added a product with "is contract"
-created a SO and added the above product
- a quotation is created (not a SO).
-when clicking on button "confirm sale" I get a warning message:
"
Odoo Warning - Warning
Please create some invoice lines.
"

link to quotation:
http://3313915-10-0-2437d7.runbot2.odoo-community.org/web#id=15&view_type=form&model=sale.order&menu_id=183&action=257

**Comment by lasley** [comment]
From @rafaelbn in https://github.com/OCA/contract/pull/49#issuecomment-358180006

> I've recorded a video: https://drive.google.com/file/d/1iwH27-uwvzSZhV2koIcEq8BiYrSkkRu-/view?usp=sharing

**Comment by rafaelbn** [comment]
Thanks @lasley !

**Comment by rafaelbn** [comment]
Hi @lasley is anyone assigned to this BUG? Let me know please. Thanks!

**Comment by pedrobaeza** [comment]
This should be solved with latest commits.

**Comment by rafaelbn** [comment]
This is not solved, tested again in runbot same problem

No news about it @lasley @tedsalmon ?

https://github.com/OCA/contract/pull/49#issuecomment-358360403

**Comment by sbidoul** [comment]
@gva-acsone I think this is the issue you have. cc/ @sbejaoui

**Comment by gva-acsone** [comment]
> @gva-acsone I think this is the issue you have. cc/ @sbejaoui

Yes, exactly, I'm encountering the same problem.

**Comment by rafaelbn** [comment]
This is solved in https://github.com/OCA/contract/pull/321 thanks to @NL66278
